openapi: 3.0.3
info:
  title: Canopi API
  version: 0.1.0
paths:
  /v1/pages/resolve:
    post:
      summary: Resolve URL to page + canonical
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url: { type: string }
              required: [url]
      responses: { "200": { description: OK } }

  /v1/anchors:
    post:
      summary: Create anchor from selection payload
      responses: { "200": { description: OK } }

  /v1/conversations:
    get:
      summary: List thread cards by pageId and filters
      responses: { "200": { description: OK } }
    post:
      summary: Create conversation (topic)
      responses: { "200": { description: OK } }

  /v1/posts:
    post:
      summary: Create post or reply
      responses: { "200": { description: OK } }

  /v1/reactions:
    post:
      summary: Toggle reaction
      responses: { "200": { description: OK } }

  /v1/presence:
    get:
      summary: Now and recent presence lists
      responses: { "200": { description: OK } }

  /v1/live/state:
    get:
      summary: Live gating state for a page
      responses: { "200": { description: OK } }
